# Generated by Django 5.1.1 on 2024-10-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_createlisting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="createlisting",
            name="user",
        ),
    ]
