# Generated by Django 5.1.1 on 2024-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_createlisting_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="createlisting",
            name="summary",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
