# Generated by Django 5.1.1 on 2024-10-03 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_createlisting_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="createlisting",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
