# Generated by Django 5.1.1 on 2024-10-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="maessage",
            new_name="message",
        ),
    ]
